// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {

  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDDjQOPU4G9QhhwUmtDyG3xyJObJjPdcB8',
    appId: '1:586427919502:web:b37a15f3e04bd6b1d5eddf',
    messagingSenderId: '586427919502',
    projectId: 'chat-d483b',
    authDomain: 'chat-d483b.firebaseapp.com',
    storageBucket: 'chat-d483b.appspot.com',
    measurementId: 'G-9H9B3PBBTM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBS5ns-2xQu5qqDB8EI0PYeSexRcYDeRgU',
    appId: '1:586427919502:android:2b7b561cd7ed3ee1d5eddf',
    messagingSenderId: '586427919502',
    projectId: 'chat-d483b',
    storageBucket: 'chat-d483b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD7ji2cw0K1wSaOBjv_fKMfbPnRL9_CPcY',
    appId: '1:586427919502:ios:96101aaf2bc836e3d5eddf',
    messagingSenderId: '586427919502',
    projectId: 'chat-d483b',
    storageBucket: 'chat-d483b.appspot.com',
    iosBundleId: 'com.example.chat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD7ji2cw0K1wSaOBjv_fKMfbPnRL9_CPcY',
    appId: '1:586427919502:ios:6e9e631727778de2d5eddf',
    messagingSenderId: '586427919502',
    projectId: 'chat-d483b',
    storageBucket: 'chat-d483b.appspot.com',
    iosBundleId: 'com.example.chat.RunnerTests',
  );
}
